"""
AquaWatch — PDF Report Generator

Generates a downloadable PDF using fpdf2.
Includes: risk summary, component scores, growth rate, advisory, timestamp.
"""

from fpdf import FPDF
from datetime import datetime
from typing import Dict
import io


class AquaWatchReport(FPDF):
    """Custom FPDF subclass with header/footer."""

    def header(self):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(30, 100, 180)
        self.cell(0, 10, "AquaWatch — Water Contamination Risk Report", align="C")
        self.ln(2)
        self.set_draw_color(30, 100, 180)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by AquaWatch — {datetime.now().strftime('%Y-%m-%d %H:%M UTC')} — Page {self.page_no()}", align="C")


def generate_pdf_report(
    location: Dict,
    risk_result: Dict,
    feature_vector: Dict,
    growth_rate: Dict,
    forecast: Dict,
    trend: Dict,
    who_info: Dict,
) -> bytes:
    """
    Generate a PDF report and return as bytes.

    Returns
    -------
    bytes — PDF file content for st.download_button
    """
    pdf = AquaWatchReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    lat = location.get("lat", 0)
    lon = location.get("lon", 0)
    now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")

    risk_score  = risk_result.get("risk_score", 0)
    risk_level  = risk_result.get("risk_level", "SAFE")
    who_sev     = risk_result.get("who_severity", "low").replace("_", " ").title()
    cells       = risk_result.get("estimated_cells_per_ml", 0)
    advisory    = risk_result.get("advisory", "")
    confidence  = risk_result.get("confidence", "MEDIUM")
    comp_scores = risk_result.get("component_scores", {})

    # ------------------------------------------------------------------
    # Section 1: Location & Summary
    # ------------------------------------------------------------------
    _section_title(pdf, "1. Location & Assessment Summary")
    _kv(pdf, "Coordinates", f"{lat:.4f}°, {lon:.4f}°")
    _kv(pdf, "Assessment Date", now)
    _kv(pdf, "Overall Risk Score", f"{risk_score:.0f} / 100  [{risk_level}]")
    _kv(pdf, "WHO Severity Level", who_sev)
    _kv(pdf, "Estimated Cyanobacteria", f"{cells:,} cells/mL")
    _kv(pdf, "Confidence", confidence)
    pdf.ln(4)

    # ------------------------------------------------------------------
    # Section 2: Component Scores
    # ------------------------------------------------------------------
    _section_title(pdf, "2. Risk Component Scores (0–100)")
    for name, score in comp_scores.items():
        bar_width = int(score * 1.2)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(45, 6, f"{name}:", ln=False)
        pdf.set_fill_color(*_score_rgb(score))
        pdf.cell(bar_width, 6, "", fill=True, ln=False)
        pdf.set_fill_color(220, 220, 220)
        pdf.cell(max(0, 120 - bar_width), 6, "", fill=True, ln=False)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(20, 6, f" {score:.0f}", ln=True)
    pdf.ln(3)

    # ------------------------------------------------------------------
    # Section 3: Growth Rate
    # ------------------------------------------------------------------
    _section_title(pdf, "3. Biological Growth Rate (Monod Kinetics)")
    mu      = growth_rate.get("mu_per_day", 0)
    dbl     = growth_rate.get("doubling_time_hours")
    lim     = growth_rate.get("limiting_factor", "Unknown")
    _kv(pdf, "Specific Growth Rate (µ)", f"{mu:.4f} per day")
    _kv(pdf, "Doubling Time", f"{dbl:.0f} hours" if dbl else "No significant growth")
    _kv(pdf, "Primary Limiting Factor", lim)
    _kv(pdf, "f(T) Temperature",  f"{growth_rate.get('f_temperature', 0):.3f}")
    _kv(pdf, "f(N) Nutrients",    f"{growth_rate.get('f_nutrients', 0):.3f}")
    _kv(pdf, "f(L) Light",        f"{growth_rate.get('f_light', 0):.3f}")
    _kv(pdf, "f(S) Stagnation",   f"{growth_rate.get('f_stagnation', 0):.3f}")
    pdf.ln(3)

    # ------------------------------------------------------------------
    # Section 4: 7-Day Forecast
    # ------------------------------------------------------------------
    _section_title(pdf, "4. 7-Day Risk Forecast")
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(230, 240, 255)
    pdf.cell(45, 6, "Date", border=1, fill=True)
    pdf.cell(35, 6, "Risk Score", border=1, fill=True)
    pdf.cell(50, 6, "WHO Severity", border=1, fill=True)
    pdf.cell(35, 6, "Temp (°C)", border=1, fill=True, ln=True)

    pdf.set_font("Helvetica", "", 9)
    dates     = forecast.get("dates", [])
    fscores   = forecast.get("risk_scores", [])
    fsev      = forecast.get("who_severities", [])
    ftemps    = forecast.get("temperatures", [])
    for i in range(min(len(dates), 8)):
        fs = fscores[i] if i < len(fscores) else 0
        r, g, b = _score_rgb(fs)
        pdf.set_fill_color(r, g, b)
        fill = True if i % 2 == 0 else False
        pdf.cell(45, 5, str(dates[i]), border=1)
        pdf.cell(35, 5, f"{fs:.0f}", border=1)
        pdf.cell(50, 5, str(fsev[i]).replace("_", " ").title() if i < len(fsev) else "-", border=1)
        pdf.cell(35, 5, f"{ftemps[i]:.1f}" if i < len(ftemps) else "-", border=1, ln=True)
    pdf.ln(4)

    # ------------------------------------------------------------------
    # Section 5: Trend Analysis
    # ------------------------------------------------------------------
    _section_title(pdf, "5. 30-Day Trend Analysis (Mann-Kendall)")
    _kv(pdf, "Trend Direction", trend.get("trend", "STABLE"))
    _kv(pdf, "Sen's Slope", f"{trend.get('slope_per_day', 0):.3f} points/day")
    _kv(pdf, "p-value", f"{trend.get('p_value', 1.0):.4f}")
    _kv(pdf, "Statistically Significant", "Yes" if trend.get("significant") else "No")
    pdf.ln(3)

    # ------------------------------------------------------------------
    # Section 6: Health Advisory
    # ------------------------------------------------------------------
    _section_title(pdf, "6. Health Advisory")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_fill_color(250, 240, 230)
    pdf.multi_cell(0, 6, advisory, fill=True, border=1)
    pdf.ln(4)

    # ------------------------------------------------------------------
    # Section 7: Methodology Note
    # ------------------------------------------------------------------
    _section_title(pdf, "7. Scientific Methodology")
    pdf.set_font("Helvetica", "", 9)
    note = (
        "Risk scores are computed using six interconnected mathematical models: "
        "(1) Temperature anomaly detection via z-score analysis against a 5-year historical baseline; "
        "(2) Nutrient loading proxy from ESA WorldCover land-use classification and rainfall delivery, "
        "calibrated using Beaulac & Reckhow (1982) nutrient export coefficients; "
        "(3) Hydrological stagnation index from wind mixing, rainfall deficit, and thermal stratification proxy; "
        "(4) Light availability from UV index, astronomical photoperiod, and cloud suppression; "
        "(5) Biological growth rate using Monod kinetics and Gaussian temperature response curves "
        "calibrated for Microcystis aeruginosa (Robarts & Zohary 1987); "
        "(6) Final bloom probability via weighted geometric mean ensuring any single limiting factor "
        "near zero collapses the risk score. "
        "CyFi (NASA/DrivenData) satellite cyanobacteria detection is used as a validation anchor. "
        "Risk levels are mapped directly to WHO recreational water safety thresholds (WHO 2003)."
    )
    pdf.multi_cell(0, 5, note)

    # Render to bytes
    return bytes(pdf.output())


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
def _section_title(pdf: FPDF, title: str):
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 80, 160)
    pdf.cell(0, 8, title, ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 10)


def _kv(pdf: FPDF, key: str, value: str):
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(65, 6, f"{key}:", ln=False)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, str(value), ln=True)


def _score_rgb(score: float):
    """Return (R,G,B) tuple based on risk score."""
    if score < 25:
        return (212, 239, 223)
    elif score < 50:
        return (253, 247, 213)
    elif score < 75:
        return (253, 224, 193)
    else:
        return (250, 215, 210)
